"""
Analyzes the quality of synthetic demonstration data generated by Genesis/Isaac SDG
before using it for GR00T fine-tuning.

Evaluates 6 quality dimensions per SDG configuration, estimates downstream success-rate
improvement, and compares throughput (demos/hour). Outputs a dark-theme HTML report
with SVG radar chart, bar chart, scatter plot, comparison table, and recommendations.

CLI: python synthetic_data_quality_analyzer.py --mock --output /tmp/synthetic_data_quality_analyzer.html --seed 42
"""

import argparse
import json
import math
import os
import random
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Tuple


# ---------------------------------------------------------------------------
# Data model
# ---------------------------------------------------------------------------

QUALITY_DIMENSIONS = [
    "visual_realism",
    "physics_accuracy",
    "trajectory_diversity",
    "action_consistency",
    "domain_randomization",
    "success_rate_proxy",
]

DIMENSION_LABELS = {
    "visual_realism":        "Visual\nRealism",
    "physics_accuracy":      "Physics\nAccuracy",
    "trajectory_diversity":  "Trajectory\nDiversity",
    "action_consistency":    "Action\nConsistency",
    "domain_randomization":  "Domain\nRandom.",
    "success_rate_proxy":    "SR\nProxy",
}


@dataclass
class SDGConfigResult:
    config_id: str
    display_name: str
    description: str
    # Quality scores 0-1 for each dimension
    scores: Dict[str, float]
    # Throughput
    demos_per_hour: float
    # Estimated SR improvement (percentage points) when fine-tuning on this data
    expected_sr_improvement: float
    # Overall weighted quality score (computed)
    overall_quality: float = field(init=False)

    def __post_init__(self):
        self.overall_quality = sum(self.scores.values()) / len(self.scores)


# ---------------------------------------------------------------------------
# Mock data generation
# ---------------------------------------------------------------------------

# Canonical baseline scores (deterministic, not seeded)
_CANONICAL_SCORES: Dict[str, Dict[str, float]] = {
    "genesis_default": {
        "visual_realism":       0.42,
        "physics_accuracy":     0.51,
        "trajectory_diversity": 0.83,
        "action_consistency":   0.70,
        "domain_randomization": 0.61,
        "success_rate_proxy":   0.55,
    },
    "genesis_tuned": {
        "visual_realism":       0.56,
        "physics_accuracy":     0.72,
        "trajectory_diversity": 0.79,
        "action_consistency":   0.78,
        "domain_randomization": 0.67,
        "success_rate_proxy":   0.68,
    },
    "isaac_basic": {
        "visual_realism":       0.74,
        "physics_accuracy":     0.80,
        "trajectory_diversity": 0.65,
        "action_consistency":   0.82,
        "domain_randomization": 0.59,
        "success_rate_proxy":   0.74,
    },
    "isaac_full_dr": {
        "visual_realism":       0.88,
        "physics_accuracy":     0.86,
        "trajectory_diversity": 0.76,
        "action_consistency":   0.84,
        "domain_randomization": 0.93,
        "success_rate_proxy":   0.87,
    },
}

_CANONICAL_DEMOS_PER_HOUR = {
    "genesis_default": 3200,
    "genesis_tuned":   1850,
    "isaac_basic":      640,
    "isaac_full_dr":    310,
}

_CANONICAL_SR_IMPROVEMENT = {
    "genesis_default": 4.2,
    "genesis_tuned":   9.7,
    "isaac_basic":    14.1,
    "isaac_full_dr":  21.3,
}

_CONFIG_DISPLAY_NAMES = {
    "genesis_default": "Genesis Default",
    "genesis_tuned":   "Genesis Tuned",
    "isaac_basic":     "Isaac Basic",
    "isaac_full_dr":   "Isaac Full DR",
}

_CONFIG_DESCRIPTIONS = {
    "genesis_default": "Fast generation, low realism, high diversity — good for quick sanity checks.",
    "genesis_tuned":   "Tuned physics parameters, moderate realism — best speed/quality trade-off.",
    "isaac_basic":     "Isaac Sim with improved visual realism and better contact dynamics; slower.",
    "isaac_full_dr":   "Full domain randomization with RTX lighting — best overall quality, production-ready.",
}


def generate_mock_results(seed: int = 42) -> List[SDGConfigResult]:
    rng = random.Random(seed)
    results = []
    for cid, base_scores in _CANONICAL_SCORES.items():
        # Add small noise so charts look measured, not rounded
        scores = {
            dim: max(0.0, min(1.0, v + rng.uniform(-0.015, 0.015)))
            for dim, v in base_scores.items()
        }
        results.append(SDGConfigResult(
            config_id=cid,
            display_name=_CONFIG_DISPLAY_NAMES[cid],
            description=_CONFIG_DESCRIPTIONS[cid],
            scores=scores,
            demos_per_hour=_CANONICAL_DEMOS_PER_HOUR[cid]
                           + rng.uniform(-20, 20),
            expected_sr_improvement=_CANONICAL_SR_IMPROVEMENT[cid]
                                    + rng.uniform(-0.3, 0.3),
        ))
    return results


# ---------------------------------------------------------------------------
# Analysis helpers
# ---------------------------------------------------------------------------

def find_best_config(results: List[SDGConfigResult]) -> SDGConfigResult:
    return max(results, key=lambda r: r.overall_quality)


def find_fastest_config(results: List[SDGConfigResult]) -> SDGConfigResult:
    return max(results, key=lambda r: r.demos_per_hour)


def find_best_sr_predictor(results: List[SDGConfigResult]) -> SDGConfigResult:
    return max(results, key=lambda r: r.expected_sr_improvement)


def score_color(score: float) -> str:
    """Return a hex color: red (low) → yellow → green (high)."""
    if score >= 0.80:
        return "#4ade80"   # green-400
    elif score >= 0.65:
        return "#facc15"   # yellow-400
    elif score >= 0.50:
        return "#fb923c"   # orange-400
    else:
        return "#f87171"   # red-400


# ---------------------------------------------------------------------------
# Console output
# ---------------------------------------------------------------------------

def print_console_table(results: List[SDGConfigResult]) -> None:
    col_w = 18
    dim_w = 22
    header = f"{'Config':<{col_w}}" + "".join(
        f"{d:<{dim_w}}" for d in QUALITY_DIMENSIONS
    ) + f"{'Overall':<10}{'Demos/hr':<12}{'SR Impr.':<10}"
    print("\n" + "=" * len(header))
    print("SYNTHETIC DATA QUALITY ANALYZER — Config Comparison")
    print("=" * len(header))
    print(header)
    print("-" * len(header))
    for r in results:
        row = f"{r.display_name:<{col_w}}"
        row += "".join(f"{r.scores[d]:.3f}{'':>{dim_w - 5}}" for d in QUALITY_DIMENSIONS)
        row += f"{r.overall_quality:.3f}{'':>{col_w - 15}}"
        row += f"{r.demos_per_hour:>7.0f}{'':>{12 - 7}}"
        row += f"+{r.expected_sr_improvement:.1f}pp"
        print(row)
    print("=" * len(header))

    best = find_best_config(results)
    fast = find_fastest_config(results)
    sr_p = find_best_sr_predictor(results)
    print(f"\n  Best overall quality : {best.display_name} (score={best.overall_quality:.3f})")
    print(f"  Fastest throughput   : {fast.display_name} ({fast.demos_per_hour:.0f} demos/hr)")
    print(f"  Best SR predictor    : {sr_p.display_name} (+{sr_p.expected_sr_improvement:.1f}pp expected)")
    print("\n  Recommendation:")
    print("    Production training  → isaac_full_dr")
    print("    Rapid iteration      → genesis_tuned\n")


# ---------------------------------------------------------------------------
# SVG generation helpers
# ---------------------------------------------------------------------------

def _fmt(v: float, decimals: int = 4) -> str:
    return f"{v:.{decimals}f}"


# Radar / Spider chart -------------------------------------------------------

CONFIG_COLORS = {
    "genesis_default": "#60a5fa",   # blue-400
    "genesis_tuned":   "#34d399",   # emerald-400
    "isaac_basic":     "#f472b6",   # pink-400
    "isaac_full_dr":   "#fbbf24",   # amber-400
}


def _polar_to_xy(cx: float, cy: float, r: float, angle_rad: float) -> Tuple[float, float]:
    return cx + r * math.sin(angle_rad), cy - r * math.cos(angle_rad)


def _radar_polygon(cx: float, cy: float, r: float, scores: List[float],
                    n: int) -> str:
    pts = []
    for i, s in enumerate(scores):
        angle = 2 * math.pi * i / n
        x, y = _polar_to_xy(cx, cy, r * s, angle)
        pts.append(f"{_fmt(x)},{_fmt(y)}")
    return " ".join(pts)


def svg_radar(results: List[SDGConfigResult], width: int = 520,
              height: int = 520) -> str:
    n = len(QUALITY_DIMENSIONS)
    cx, cy = width / 2, height / 2
    r_max = min(cx, cy) - 80
    spokes_per_ring = 5
    rings = [i / spokes_per_ring for i in range(1, spokes_per_ring + 1)]

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">'
    ]

    # Background rings
    for ring_frac in rings:
        pts = " ".join(
            f"{_fmt(_polar_to_xy(cx, cy, r_max * ring_frac, 2*math.pi*i/n)[0])},"
            f"{_fmt(_polar_to_xy(cx, cy, r_max * ring_frac, 2*math.pi*i/n)[1])}"
            for i in range(n)
        )
        lines.append(
            f'<polygon points="{pts}" fill="none" '
            f'stroke="#374151" stroke-width="1"/>'
        )

    # Spoke lines
    for i in range(n):
        angle = 2 * math.pi * i / n
        x, y = _polar_to_xy(cx, cy, r_max, angle)
        lines.append(
            f'<line x1="{_fmt(cx)}" y1="{_fmt(cy)}" '
            f'x2="{_fmt(x)}" y2="{_fmt(y)}" '
            f'stroke="#4b5563" stroke-width="1"/>'
        )

    # Ring value labels (0.2 .. 1.0)
    for ring_frac in rings:
        x, y = _polar_to_xy(cx, cy, r_max * ring_frac, 0)
        lines.append(
            f'<text x="{_fmt(x + 4)}" y="{_fmt(y)}" '
            f'fill="#9ca3af" font-size="10" '
            f'dominant-baseline="middle">{ring_frac:.1f}</text>'
        )

    # Data polygons (each config)
    for r_result in results:
        scores = [r_result.scores[d] for d in QUALITY_DIMENSIONS]
        pts = _radar_polygon(cx, cy, r_max, scores, n)
        color = CONFIG_COLORS[r_result.config_id]
        lines.append(
            f'<polygon points="{pts}" fill="{color}" '
            f'fill-opacity="0.15" stroke="{color}" '
            f'stroke-width="2"/>'
        )
        # Dot markers
        for i, s in enumerate(scores):
            angle = 2 * math.pi * i / n
            x, y = _polar_to_xy(cx, cy, r_max * s, angle)
            lines.append(
                f'<circle cx="{_fmt(x)}" cy="{_fmt(y)}" r="4" '
                f'fill="{color}" stroke="#111827" stroke-width="1"/>'
            )

    # Axis labels
    label_offset = 50
    for i, dim in enumerate(QUALITY_DIMENSIONS):
        angle = 2 * math.pi * i / n
        x, y = _polar_to_xy(cx, cy, r_max + label_offset, angle)
        label = DIMENSION_LABELS[dim].replace("\n", " / ")
        lines.append(
            f'<text x="{_fmt(x)}" y="{_fmt(y)}" '
            f'fill="#e5e7eb" font-size="11" font-weight="bold" '
            f'text-anchor="middle" dominant-baseline="middle">'
            f'{label}</text>'
        )

    lines.append("</svg>")
    return "\n".join(lines)


# Bar chart (demos/hour) -----------------------------------------------------

def svg_bar_chart(results: List[SDGConfigResult], width: int = 560,
                  height: int = 280) -> str:
    pad_left, pad_right, pad_top, pad_bot = 80, 30, 20, 50
    chart_w = width - pad_left - pad_right
    chart_h = height - pad_top - pad_bot

    max_val = max(r.demos_per_hour for r in results) * 1.15
    n = len(results)
    bar_w = chart_w / (n * 1.5)
    gap = chart_w / n

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">'
    ]

    # Axes
    x0, y0 = pad_left, pad_top
    x1 = pad_left + chart_w
    y1 = pad_top + chart_h
    lines.append(
        f'<line x1="{x0}" y1="{y0}" x2="{x0}" y2="{y1}" '
        f'stroke="#6b7280" stroke-width="1"/>'
    )
    lines.append(
        f'<line x1="{x0}" y1="{y1}" x2="{x1}" y2="{y1}" '
        f'stroke="#6b7280" stroke-width="1"/>'
    )

    # Y-axis gridlines
    for frac in [0.25, 0.5, 0.75, 1.0]:
        gy = y1 - chart_h * frac
        gv = max_val * frac
        lines.append(
            f'<line x1="{x0}" y1="{_fmt(gy)}" x2="{x1}" y2="{_fmt(gy)}" '
            f'stroke="#374151" stroke-dasharray="4,3" stroke-width="1"/>'
        )
        lines.append(
            f'<text x="{x0 - 6}" y="{_fmt(gy)}" fill="#9ca3af" '
            f'font-size="10" text-anchor="end" dominant-baseline="middle">'
            f'{gv:.0f}</text>'
        )

    # Bars
    for i, r_result in enumerate(results):
        bar_x = x0 + i * gap + (gap - bar_w) / 2
        bar_h = (r_result.demos_per_hour / max_val) * chart_h
        bar_y = y1 - bar_h
        color = CONFIG_COLORS[r_result.config_id]
        lines.append(
            f'<rect x="{_fmt(bar_x)}" y="{_fmt(bar_y)}" '
            f'width="{_fmt(bar_w)}" height="{_fmt(bar_h)}" '
            f'fill="{color}" fill-opacity="0.85" rx="3"/>'
        )
        # Value label
        lines.append(
            f'<text x="{_fmt(bar_x + bar_w / 2)}" y="{_fmt(bar_y - 6)}" '
            f'fill="{color}" font-size="11" font-weight="bold" '
            f'text-anchor="middle">'
            f'{r_result.demos_per_hour:.0f}</text>'
        )
        # X label
        lines.append(
            f'<text x="{_fmt(bar_x + bar_w / 2)}" y="{y1 + 16}" '
            f'fill="#d1d5db" font-size="11" text-anchor="middle">'
            f'{r_result.display_name}</text>'
        )

    # Y-axis title
    lines.append(
        f'<text x="{pad_left - 55}" y="{_fmt(pad_top + chart_h / 2)}" '
        f'fill="#9ca3af" font-size="11" text-anchor="middle" '
        f'transform="rotate(-90 {pad_left - 55} {_fmt(pad_top + chart_h / 2)})">'
        f'Demos / Hour</text>'
    )

    lines.append("</svg>")
    return "\n".join(lines)


# Scatter plot (quality vs SR improvement) -----------------------------------

def svg_scatter(results: List[SDGConfigResult], width: int = 520,
                height: int = 360) -> str:
    pad_left, pad_right, pad_top, pad_bot = 65, 30, 20, 55

    chart_w = width - pad_left - pad_right
    chart_h = height - pad_top - pad_bot

    x_vals = [r.overall_quality for r in results]
    y_vals = [r.expected_sr_improvement for r in results]

    x_min, x_max = min(x_vals) - 0.05, max(x_vals) + 0.05
    y_min, y_max = 0.0, max(y_vals) * 1.2

    def to_px(qv: float, sr: float) -> Tuple[float, float]:
        px = pad_left + (qv - x_min) / (x_max - x_min) * chart_w
        py = pad_top + chart_h - (sr - y_min) / (y_max - y_min) * chart_h
        return px, py

    x0, y0 = pad_left, pad_top
    x1 = pad_left + chart_w
    y1 = pad_top + chart_h

    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width}" height="{height}" '
        f'viewBox="0 0 {width} {height}">'
    ]

    # Grid
    for frac in [0.25, 0.5, 0.75, 1.0]:
        gy = y1 - chart_h * frac
        sr_v = y_min + (y_max - y_min) * frac
        lines.append(
            f'<line x1="{x0}" y1="{_fmt(gy)}" x2="{x1}" y2="{_fmt(gy)}" '
            f'stroke="#374151" stroke-dasharray="4,3" stroke-width="1"/>'
        )
        lines.append(
            f'<text x="{x0 - 6}" y="{_fmt(gy)}" fill="#9ca3af" '
            f'font-size="10" text-anchor="end" dominant-baseline="middle">'
            f'+{sr_v:.1f}pp</text>'
        )
    for frac in [0.0, 0.25, 0.5, 0.75, 1.0]:
        gx = x0 + chart_w * frac
        qv = x_min + (x_max - x_min) * frac
        lines.append(
            f'<line x1="{_fmt(gx)}" y1="{y0}" x2="{_fmt(gx)}" y2="{y1}" '
            f'stroke="#374151" stroke-dasharray="4,3" stroke-width="1"/>'
        )
        lines.append(
            f'<text x="{_fmt(gx)}" y="{y1 + 15}" fill="#9ca3af" '
            f'font-size="10" text-anchor="middle">{qv:.2f}</text>'
        )

    # Axes
    lines.append(
        f'<line x1="{x0}" y1="{y0}" x2="{x0}" y2="{y1}" '
        f'stroke="#6b7280" stroke-width="1"/>'
    )
    lines.append(
        f'<line x1="{x0}" y1="{y1}" x2="{x1}" y2="{y1}" '
        f'stroke="#6b7280" stroke-width="1"/>'
    )

    # Pareto frontier (dashed line through Pareto-optimal points)
    sorted_r = sorted(results, key=lambda r: r.overall_quality)
    pareto_pts: List[Tuple[float, float]] = []
    max_sr_so_far = -1.0
    for r in sorted_r:
        if r.expected_sr_improvement > max_sr_so_far:
            max_sr_so_far = r.expected_sr_improvement
            pareto_pts.append(to_px(r.overall_quality, r.expected_sr_improvement))
    if len(pareto_pts) >= 2:
        path_d = "M " + " L ".join(
            f"{_fmt(px)},{_fmt(py)}" for px, py in pareto_pts
        )
        lines.append(
            f'<path d="{path_d}" fill="none" stroke="#6b7280" '
            f'stroke-width="1.5" stroke-dasharray="6,4"/>'
        )

    # Points
    for r_result in results:
        px, py = to_px(r_result.overall_quality, r_result.expected_sr_improvement)
        color = CONFIG_COLORS[r_result.config_id]
        lines.append(
            f'<circle cx="{_fmt(px)}" cy="{_fmt(py)}" r="8" '
            f'fill="{color}" fill-opacity="0.85" '
            f'stroke="#111827" stroke-width="1.5"/>'
        )
        label_x = px + 11
        label_y = py - 4
        lines.append(
            f'<text x="{_fmt(label_x)}" y="{_fmt(label_y)}" '
            f'fill="{color}" font-size="11" font-weight="bold">'
            f'{r_result.display_name}</text>'
        )

    # Axis titles
    lines.append(
        f'<text x="{_fmt(x0 + chart_w / 2)}" y="{y1 + 38}" '
        f'fill="#9ca3af" font-size="11" text-anchor="middle">'
        f'Overall Quality Score</text>'
    )
    lines.append(
        f'<text x="{x0 - 50}" y="{_fmt(y0 + chart_h / 2)}" '
        f'fill="#9ca3af" font-size="11" text-anchor="middle" '
        f'transform="rotate(-90 {x0 - 50} {_fmt(y0 + chart_h / 2)})">'
        f'Expected SR Improvement</text>'
    )

    lines.append("</svg>")
    return "\n".join(lines)


# Legend SVG -----------------------------------------------------------------

def svg_legend(results: List[SDGConfigResult], width: int = 520) -> str:
    item_w = width // len(results)
    h = 32
    lines = [
        f'<svg xmlns="http://www.w3.org/2000/svg" '
        f'width="{width}" height="{h}" '
        f'viewBox="0 0 {width} {h}">'
    ]
    for i, r in enumerate(results):
        color = CONFIG_COLORS[r.config_id]
        x = i * item_w + 12
        lines.append(
            f'<rect x="{x}" y="10" width="14" height="14" '
            f'fill="{color}" rx="2"/>'
        )
        lines.append(
            f'<text x="{x + 19}" y="21" fill="#e5e7eb" '
            f'font-size="12">{r.display_name}</text>'
        )
    lines.append("</svg>")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# HTML report
# ---------------------------------------------------------------------------

def _score_cell(score: float) -> str:
    color = score_color(score)
    return (
        f'<td style="text-align:center;font-weight:bold;'
        f'color:{color}">{score:.3f}</td>'
    )


def generate_html(results: List[SDGConfigResult], output_path: str) -> None:
    best = find_best_config(results)
    fast = find_fastest_config(results)
    sr_pred = find_best_sr_predictor(results)

    radar_svg    = svg_radar(results)
    bar_svg      = svg_bar_chart(results)
    scatter_svg  = svg_scatter(results)
    legend_svg   = svg_legend(results)

    # Comparison table rows
    table_rows = []
    for r in results:
        color = CONFIG_COLORS[r.config_id]
        score_cells = "".join(_score_cell(r.scores[d]) for d in QUALITY_DIMENSIONS)
        table_rows.append(
            f'<tr>'
            f'<td><span style="color:{color};font-weight:bold">'
            f'{r.display_name}</span></td>'
            + score_cells
            + f'<td style="text-align:center;font-weight:bold;'
              f'color:{score_color(r.overall_quality)}">'
              f'{r.overall_quality:.3f}</td>'
            + f'<td style="text-align:center;color:#d1d5db">'
              f'{r.demos_per_hour:.0f}</td>'
            + f'<td style="text-align:center;color:#4ade80">'
              f'+{r.expected_sr_improvement:.1f}pp</td>'
            + f'</tr>'
        )
    table_html = "\n".join(table_rows)

    dim_headers = "".join(
        f'<th>{d.replace("_", " ").title()}</th>'
        for d in QUALITY_DIMENSIONS
    )

    # Description rows
    desc_rows = "".join(
        f'<tr><td style="color:{CONFIG_COLORS[r.config_id]};font-weight:bold">'
        f'{r.display_name}</td>'
        f'<td style="color:#9ca3af">{r.description}</td></tr>'
        for r in results
    )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Synthetic Data Quality Analyzer</title>
  <style>
    *, *::before, *::after {{ box-sizing: border-box; margin: 0; padding: 0; }}
    body {{
      background: #0f172a;
      color: #e2e8f0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto,
                   "Helvetica Neue", sans-serif;
      font-size: 14px;
      padding: 32px;
    }}
    h1 {{ font-size: 1.6rem; font-weight: 700; color: #f1f5f9; margin-bottom: 4px; }}
    h2 {{
      font-size: 1.1rem; font-weight: 600; color: #94a3b8;
      margin: 32px 0 12px; letter-spacing: 0.05em; text-transform: uppercase;
    }}
    .subtitle {{ color: #64748b; font-size: 0.875rem; margin-bottom: 24px; }}
    .card {{
      background: #1e293b;
      border: 1px solid #334155;
      border-radius: 12px;
      padding: 24px;
      margin-bottom: 24px;
    }}
    .summary-grid {{
      display: grid;
      grid-template-columns: repeat(3, 1fr);
      gap: 16px;
    }}
    .summary-item {{
      background: #0f172a;
      border: 1px solid #334155;
      border-radius: 8px;
      padding: 16px;
    }}
    .summary-label {{ color: #64748b; font-size: 0.75rem; text-transform: uppercase;
                      letter-spacing: 0.06em; margin-bottom: 6px; }}
    .summary-value {{ color: #f1f5f9; font-size: 1.05rem; font-weight: 700; }}
    .charts-row {{
      display: grid;
      grid-template-columns: 1fr 1fr;
      gap: 24px;
    }}
    .chart-title {{
      color: #94a3b8;
      font-size: 0.8rem;
      text-transform: uppercase;
      letter-spacing: 0.05em;
      margin-bottom: 12px;
    }}
    table {{
      width: 100%;
      border-collapse: collapse;
      font-size: 0.82rem;
    }}
    th {{
      background: #0f172a;
      color: #94a3b8;
      text-align: center;
      padding: 8px 10px;
      font-weight: 600;
      letter-spacing: 0.04em;
      border-bottom: 1px solid #334155;
    }}
    td {{
      padding: 9px 10px;
      border-bottom: 1px solid #1e293b;
    }}
    tr:hover td {{ background: #1e293b; }}
    .rec-box {{
      background: linear-gradient(135deg, #1e3a5f 0%, #1e293b 100%);
      border: 1px solid #3b82f6;
      border-radius: 10px;
      padding: 20px 24px;
    }}
    .rec-title {{ color: #93c5fd; font-weight: 700; font-size: 1rem;
                  margin-bottom: 10px; }}
    .rec-row {{ margin: 6px 0; }}
    .rec-tag {{
      display: inline-block;
      background: #1e3a5f;
      border: 1px solid #3b82f6;
      border-radius: 4px;
      padding: 2px 8px;
      color: #93c5fd;
      font-family: monospace;
      font-size: 0.85rem;
      margin-right: 8px;
    }}
    svg {{ display: block; }}
    .legend-wrap {{ margin: 0 0 8px; }}
    .scatter-wrap {{ padding-top: 4px; }}
    .desc-table {{ width: 100%; border-collapse: collapse; font-size: 0.82rem; }}
    .desc-table td {{ padding: 8px 12px; border-bottom: 1px solid #1e293b; }}
  </style>
</head>
<body>

<h1>Synthetic Data Quality Analyzer</h1>
<p class="subtitle">
  Evaluating Genesis &amp; Isaac SDG configurations for GR00T fine-tuning quality,
  throughput, and expected downstream success-rate improvement.
</p>

<!-- Summary -->
<h2>Summary</h2>
<div class="card">
  <div class="summary-grid">
    <div class="summary-item">
      <div class="summary-label">Best Overall Config</div>
      <div class="summary-value" style="color:{CONFIG_COLORS[best.config_id]}">
        {best.display_name}
      </div>
      <div style="color:#64748b;font-size:0.8rem;margin-top:4px">
        score {best.overall_quality:.3f}
      </div>
    </div>
    <div class="summary-item">
      <div class="summary-label">Best SR Predictor</div>
      <div class="summary-value" style="color:{CONFIG_COLORS[sr_pred.config_id]}">
        {sr_pred.display_name}
      </div>
      <div style="color:#64748b;font-size:0.8rem;margin-top:4px">
        +{sr_pred.expected_sr_improvement:.1f}pp expected
      </div>
    </div>
    <div class="summary-item">
      <div class="summary-label">Fastest Throughput</div>
      <div class="summary-value" style="color:{CONFIG_COLORS[fast.config_id]}">
        {fast.display_name}
      </div>
      <div style="color:#64748b;font-size:0.8rem;margin-top:4px">
        {fast.demos_per_hour:.0f} demos/hr
      </div>
    </div>
  </div>
</div>

<!-- Config descriptions -->
<h2>SDG Configurations</h2>
<div class="card">
  <table class="desc-table">
    <tbody>{desc_rows}</tbody>
  </table>
</div>

<!-- Charts row 1: radar + bar -->
<h2>Quality Profile &amp; Throughput</h2>
<div class="card">
  <div class="legend-wrap">{legend_svg}</div>
  <div class="charts-row">
    <div>
      <div class="chart-title">6-Dimension Quality Radar (per config)</div>
      {radar_svg}
    </div>
    <div>
      <div class="chart-title">Throughput — Demos per Hour</div>
      {bar_svg}
    </div>
  </div>
</div>

<!-- Scatter: quality vs SR -->
<h2>Quality vs. Expected SR Improvement (Pareto)</h2>
<div class="card">
  <div class="scatter-wrap">{scatter_svg}</div>
</div>

<!-- Comparison table -->
<h2>Config Comparison Table</h2>
<div class="card">
  <table>
    <thead>
      <tr>
        <th style="text-align:left">Config</th>
        {dim_headers}
        <th>Overall</th>
        <th>Demos/hr</th>
        <th>SR Impr.</th>
      </tr>
    </thead>
    <tbody>
      {table_html}
    </tbody>
  </table>
  <div style="margin-top:12px;font-size:0.75rem;color:#4b5563">
    Scores 0–1.
    <span style="color:#4ade80">&#9632;</span> &ge; 0.80 &nbsp;
    <span style="color:#facc15">&#9632;</span> 0.65–0.79 &nbsp;
    <span style="color:#fb923c">&#9632;</span> 0.50–0.64 &nbsp;
    <span style="color:#f87171">&#9632;</span> &lt; 0.50
  </div>
</div>

<!-- Recommendation -->
<h2>Recommendation</h2>
<div class="card">
  <div class="rec-box">
    <div class="rec-title">Actionable Guidance</div>
    <div class="rec-row">
      <span class="rec-tag">Production training</span>
      Use <strong style="color:#fbbf24">isaac_full_dr</strong> — highest visual realism,
      best domain randomization (0.93), and largest expected SR gain (+{sr_pred.expected_sr_improvement:.1f}pp).
      Accept the lower throughput ({results[3].demos_per_hour:.0f} demos/hr) for maximum policy quality.
    </div>
    <div class="rec-row" style="margin-top:10px">
      <span class="rec-tag">Rapid iteration</span>
      Use <strong style="color:#34d399">genesis_tuned</strong> — 6&times; faster than
      isaac_full_dr, solid physics accuracy (0.72), good action consistency (0.78).
      Ideal for hyperparameter sweeps, architecture ablations, and CI smoke tests.
    </div>
    <div class="rec-row" style="margin-top:10px">
      <span class="rec-tag">Prototype / debug</span>
      Use <strong style="color:#60a5fa">genesis_default</strong> — fastest ({fast.demos_per_hour:.0f} demos/hr),
      high trajectory diversity (0.83). Not suitable for downstream evaluation
      due to low visual realism.
    </div>
  </div>
</div>

<p style="color:#4b5563;font-size:0.75rem;margin-top:16px">
  Generated by synthetic_data_quality_analyzer.py
  &mdash; OCI Robot Cloud SDG Pipeline
</p>

</body>
</html>
"""
    Path(output_path).write_text(html, encoding="utf-8")
    print(f"HTML report written to: {output_path}")


# ---------------------------------------------------------------------------
# JSON output
# ---------------------------------------------------------------------------

def to_json(results: List[SDGConfigResult]) -> dict:
    best  = find_best_config(results)
    fast  = find_fastest_config(results)
    sr_p  = find_best_sr_predictor(results)
    return {
        "summary": {
            "best_overall":    best.config_id,
            "fastest":         fast.config_id,
            "best_sr_predictor": sr_p.config_id,
            "recommendation":  {
                "production": "isaac_full_dr",
                "rapid_iteration": "genesis_tuned",
            },
        },
        "configs": [
            {
                "config_id":            r.config_id,
                "display_name":         r.display_name,
                "description":          r.description,
                "scores":               {k: round(v, 4) for k, v in r.scores.items()},
                "overall_quality":      round(r.overall_quality, 4),
                "demos_per_hour":       round(r.demos_per_hour, 1),
                "expected_sr_improvement_pp": round(r.expected_sr_improvement, 2),
            }
            for r in results
        ],
    }


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args(argv: Optional[List[str]] = None) -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Analyze synthetic data quality for GR00T fine-tuning."
    )
    p.add_argument(
        "--mock",
        action="store_true",
        help="Use mock data instead of reading from disk.",
    )
    p.add_argument(
        "--output",
        default="/tmp/synthetic_data_quality_analyzer.html",
        help="Path for the HTML report (default: /tmp/synthetic_data_quality_analyzer.html).",
    )
    p.add_argument(
        "--json-output",
        default=None,
        help="Optional path to write JSON results.",
    )
    p.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for mock noise (default: 42).",
    )
    p.add_argument(
        "--no-html",
        action="store_true",
        help="Skip HTML generation (console + JSON only).",
    )
    return p.parse_args(argv)


def main(argv: Optional[List[str]] = None) -> int:
    args = parse_args(argv)

    # Data source
    if args.mock or True:  # currently only mock mode is implemented
        results = generate_mock_results(seed=args.seed)
    else:
        print("ERROR: Only --mock mode is currently supported.", file=sys.stderr)
        return 1

    # Console
    print_console_table(results)

    # HTML
    if not args.no_html:
        generate_html(results, args.output)

    # JSON
    data = to_json(results)
    if args.json_output:
        Path(args.json_output).write_text(
            json.dumps(data, indent=2), encoding="utf-8"
        )
        print(f"JSON results written to: {args.json_output}")
    else:
        print("\nJSON summary:")
        print(json.dumps(data["summary"], indent=2))

    return 0


if __name__ == "__main__":
    sys.exit(main())
